socialPOD-django-master/communities/urls.py
from django.urls import path

from . import views as communities_views

app_name = "communities"

# ###############################
# NOTE: Order matters!
# ###############################

urlpatterns = [
	# ex: /communities/index/
	path('index?page=<int:page>/',communities_views.viewIndex,name="index"),

	##################
	# URLS for Posts
	##################
	# CREATING A POST
	path('posts/post-create/',communities_views.viewPostCreate,name="post-create"),
	# DELETING A POST
	path('posts/post-delete/<int:post_id>',communities_views.viewPostDelete,name="post-delete"),
	# VIEWING A POST
	path('posts/view/<str:username>/<slug:slug>/',communities_views.viewPostDetail,name="post-detail"),
	# prepare a post
	path('posts/prepare/',communities_views.viewPostPrepare,name="post-prepare"),

	##################
	# URLS for Posts Actions (Like)
	##################
	path('post-like/<int:post_id>/',communities_views.viewLikeUnlikePost,name="post-like-unlike"),

	##################
	# URLS for Posts Comments
	##################
	# ex: /communities/posts/username/slug-my-post-title/create_comment/
	path('posts/<str:username>/<slug:slug>/comment-create/',communities_views.viewCreateComment,name="comment-create"),
	# ex: /communities/posts/username/slug-my-post-title/delete_comment/
	path('posts/comment-delete/<int:comment_id>/',communities_views.viewDeleteComment,name="comment-delete"),

	##################
	# URLS for Public Profiles
	##################
	# ex: /communities/profile/username/
	path('profile/<str:username>&page=<int:page>/',communities_views.viewProfile,name="profile"),
	##################
	# URLS for Following
	##################
	path('following/add_remove_follow/<str:username>/',communities_views.viewAddRemoveFollow,name="follow-add-remove"),

	##################
	# URLS for Leaderboard
	##################
	path("leaderboard/index/",communities_views.viewLeaderboardIndex,name='leaderboard-index'),
]

socialPOD-django-master/core/urls.py
from django.urls import path

from . import views as core_views

app_name = "core"
urlpatterns = [
	# ex: /
	path('home/index&np=<int:pg_post>&nhr=<int:pg_help_req>&ndm=<int:pg_dm>/',core_views.viewIndex,name='index'),
	# ex: /about/
	path('',core_views.viewAbout,name='about'),
	# deleting notification
	path('notifications/<str:notification_type>/<int:notification_id>/delete/',core_views.viewNotificationDelete,name="notification-delete"),

	#######################
	# Tips paths
	#######################
	# reading tip
	path('tips/<int:tip_id>/read/',core_views.viewTipRead,name='tip-read'),
	# tip archive
	path('tips/archive&pg_prev_tips=<int:pg_prev_tips>/',core_views.viewTipArchive,name='tip-archive'),

	#######################
	# AJAX paths
	#######################
	path('ajax/index/posts&pg_post=<int:pg_post>&pg_hr=<int:pg_help_req>&pg_dm=<int:pg_dm>/',core_views.aGetNotifPosts,name='ajax-index-posts'),
	path('ajax/index/help_requests&pg_post=<int:pg_post>&pg_hr=<int:pg_help_req>&pg_dm=<int:pg_dm>/',core_views.aGetNotifHelpRequests,name='ajax-index-help-requests'),
	path('ajax/index/dms&pg_post=<int:pg_post>&pg_hr=<int:pg_help_req>&pg_dm=<int:pg_dm>/',core_views.aGetNotifDms,name='ajax-index-dms'),
	path('ajax/tip/archive/get_tips&pg=<int:pg_prev_tips>/',core_views.aGetTips,name="ajax-tips-archive-prev-tips"),

]

socialPOD-django-master/socialPOD_project/urls.py
from django.contrib import admin
from django.urls import path,include

# for mapping static file urls
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # admin urls
    path('admin/', admin.site.urls),

    ##############################
    # URLS for user created apps
    ##############################
    # core urls
    path('',include('core.urls')),
    # user urls
    path('users/',include('users.urls')),
    # newsfeed urls
    path('newsfeed/',include('newsfeed.urls')),
    # podcasts urls
    path('podcasts/',include('podcasts.urls')),
    # communities urls
    path('communities/',include('communities.urls')),
    # food urls
    path('food/',include('food.urls')),
    # fitness urls
    path('fitness/',include('fitness.urls')),
]


# linking media root
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

socialPOD-django-master/communities/forms.py
from django import forms


#####################################
# Necessary models
#####################################

from .models import Post, Comment



# Form for creating post
class PostForm(forms.ModelForm):
	class Meta:
		model = Post

		# the editable fields by user
		fields = [
			"title",
			"text",
		]
		exclude = ()

		# change size of form
		widgets = {
			'text':forms.Textarea(attrs={'rows':10,'cols':50,
			'style':'resize:none'}),
		}

# Form for creating Comments
class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = [
			'text',
		]
		widgets = {
			'text':forms.Textarea(attrs={'rows':2,'cols':20,
			'style':'resize:none'}),
		}

socialPOD-django-master/communities/views.py
from django.contrib.auth.decorators import login_required

#####################################
# HTML routing imports
#####################################
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
# templates
from django.template.loader import render_to_string
# json / serializers
from django.http import JsonResponse

#####################################
# django utils
#####################################
# messages
from django.contrib import messages
# time zones
from django.utils import timezone
# pagination
from django.core.paginator import Paginator, EmptyPage

#####################################
# Necessary models
#####################################
from users.models import CustomUser
from .models import Post,Comment
# notifications
from core.models import NotificationPost, NotificationUser

#####################################
# Necessary forms
#####################################
from .forms import PostForm, CommentForm
from newsfeed.forms import HelpRequestForm

# note! (08/14/22)
# rqeuest.is_ajax has recently be depreciated.
# since this is an archive, here is a new function to replace it.
def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


@login_required
def viewIndex(request,page=1):
	###################################
	# Inputs:
	# request, page for pagination
	# Outputs:
	# render
	# Utility:
	# view called for index
	###################################


	# note that create post is handled in a different view
	# we use form action to create the objects
	formPostForm = PostForm()
	formCommentForm = CommentForm()

	
	# order the posts
	# Create a dictionary of {Post:Post comments sorted}
	qsPosts = Post.objects.order_by('-pub_date')

	intPostsPerPage = 3
	# paginate based on number of posts
	paginator = Paginator(qsPosts,intPostsPerPage)	

	try:
		qsPosts = paginator.page(page)
	except EmptyPage:
		# if exceed limit go to last page
		qsPosts = paginator.page(paginator.num_pages)

	context = {
		"qsPosts":qsPosts,
		"formPostForm":formPostForm,
		"formCommentForm":formCommentForm,
	}
	# NOTE!
	# request.is_ajax() is depreciated in newer versions of django
	if is_ajax(request):
		posts_html = render_to_string(
			"communities/t/posts.html",
			{'qsPosts':qsPosts}
		)
		data = {
			'posts_html':posts_html,
			'has_next':qsPosts.has_next()
		}
		return JsonResponse(data)

	return render(request,'communities/index.html',context = context)

@login_required
def viewPostPrepare(request):
	context = {

	}

	return render(request,'communities/post_prepare.html',context=context)

@login_required
def viewPostCreate(request):
	###################################
	# Inputs:
	# request
	# Outputs:
	# redirect
	# Utility:
	# view called to create a post
	###################################
	modelPost = Post()

	formPostForm = PostForm(instance=modelPost)

	if request.method == "POST":

		# fill with post data
		formPostForm = PostForm(request.POST)

		modelCreatedPost = formPostForm.save(commit=False)

		formPostForm = PostForm(request.POST)

		if formPostForm.is_valid():
			# save the object
			user = request.user

			modelCreatedPost.author = user

			modelCreatedPost.save()

			# show message that post created
			messages.success(request, "Post created.")

			# redirect
			return redirect(reverse('communities:index',kwargs={"page":1}))
	
	context = {
		"formPostForm":formPostForm,
	}
	return redirect(reverse('communities:index',kwargs={"page":1}))

@login_required
def viewLikeUnlikePost(request,post_id):
	###################################
	# Inputs:
	# request, int
	# Outputs:
	# redirect
	# Utility:
	# view to like or unlike a post
	###################################
	modelPost = get_object_or_404(Post,id=post_id)

	if(modelPost.user_likes.filter(id=request.user.id).exists()):
		modelPost.user_likes.remove(request.user)
	else:

		modelPost.user_likes.add(request.user)

		################
		# Create a notification.
		# populate all fields
		################

		# notify that they liked post
		modelNotificationPost = NotificationPost()
		# give sender
		modelNotificationPost.sender = request.user
		# give recipient
		modelNotificationPost.recipient = modelPost.author
		# link to post
		modelNotificationPost.post = modelPost
		# give text
		modelNotificationPost.text = "{} has liked your post {}.".format(request.user,modelPost.title)
		
		modelNotificationPost.save()
	
	return redirect(reverse('communities:index',kwargs={"page":1}))

@login_required
def viewPostDetail(request, slug,username):
	###################################
	# Inputs:
	# request, str slug, str username
	# Outputs:
	# render
	# Utility:
	# view for see post by user
	###################################
	modelPostAuthor = get_object_or_404(CustomUser, username=username)
	modelPost = get_object_or_404(Post,slug=slug,author=modelPostAuthor)

	# filter only those comments that are not replies
	listmodelComments = modelPost.comments.filter(active = True).order_by("pub_date")

	# form for creating a comment
	formCommentForm = CommentForm()

	context = {
		"modelPost":modelPost,
		"listPostComments":listmodelComments,
		"formCommentForm":formCommentForm,
	}
	return render(request, 'communities/post_detail.html',context)

@login_required
def viewProfile(request, username,page=1):
	###################################
	# Inputs:
	# request, str username, page for pagination
	# Outputs:
	# render
	# Utility:
	# view called for public profile
	###################################

	modelUser = get_object_or_404(CustomUser, username = username)
	qsPosts = modelUser.created_post_set.order_by('-pub_date')

	# pagination number of posts per page
	intPostsPerPage = 3
	# paginate based on number of posts
	paginator = Paginator(qsPosts,intPostsPerPage)

	try:
		qsPosts = paginator.page(page)
	except EmptyPage:
		# if exceed limit go to last page
		qsPosts = paginator.page(paginator.num_pages)

	context = {
		"modelViewedUser": modelUser,
		"qsPosts":qsPosts,
	}

	return render(request, "communities/profile.html",context)

############
# Creating comments
# With reference to:
# https://stackoverflow.com/questions/44837733/how-to-make-add-replies-to-comments-in-django
############
@login_required
def viewCreateComment(request,username,slug):
	###################################
	# Inputs:
	# request, str username, str slug
	# Outputs:
	# redirect
	# Utility:
	# view to create comments (or replies)
	###################################
	# get the author
	modelPostAuthor = get_object_or_404(CustomUser,username = username)
	# get the post
	modelPost = get_object_or_404(Post, slug = slug,author = modelPostAuthor)

	if request.method == "POST":
		# get the current user
		modelUser = request.user

		# form for comment
		formCommentForm = CommentForm(data=request.POST)

		if formCommentForm.is_valid():
			modelParentObj = None
			# try to get parent comment id from hidden input
			try:
				intParentId = int(request.POST.get("intParentId"))
			except:
				intParentId = None
			# if parent has been submitted get the parent's id
			if intParentId:
				modelParentObj = Comment.objects.get(id=intParentId)
				# if there exists a parent
				if modelParentObj:
					# create reply
					modelReplyComment = formCommentForm.save(commit=False)
					# put user with comment
					modelReplyComment.author = modelUser
					# put the parent id in the reply
					modelReplyComment.parent = modelParentObj
					# since reply, notify the person you reply to
					modelNotificationToReply = NotificationPost()
					modelNotificationToReply.sender = request.user
					modelNotificationToReply.recipient = modelParentObj.author
					modelNotificationToReply.text = "{} has replied to your comment on post {}.".format(request.user.username,modelPost.title)
					modelNotificationToReply.post = modelPost
					modelNotificationToReply.save()

			# Else, this is a normal comment
			# create but dont save to db
			modelNewComment = formCommentForm.save(commit = False)
			modelNewComment.post = modelPost
			modelNewComment.author = modelUser
			# save
			modelNewComment.save()

			# create a notification for the other users
			# always notify the post owner
			modelNotificationToParent = NotificationPost()
			modelNotificationToParent.sender = request.user
			modelNotificationToParent.recipient = modelPost.author
			modelNotificationToParent.text= "{} has commented on your post {}.".format(request.user.username,modelPost.title)
			modelNotificationToParent.post = modelPost
			modelNotificationToParent.save()
		# if form not valid, show message
		else:
			messages.warning(request,"Message could not be sent. Please try again.")
			

	return redirect(reverse('communities:post-detail',kwargs={'username':modelPost.author.username,'slug':modelPost.slug}))

@login_required
def viewPostDelete(request,post_id):
	###################################
	# Inputs:
	# request, int
	# Outputs:
	# redirect
	# Utility:
	# view to delete posts
	###################################
	modelPost = get_object_or_404(Post, id = post_id)
	modelPostAuthor = modelPost.author

	###########
	# always check if the user that is calling the function is the user who owns the thing
	###########
	if request.user == modelPostAuthor:
		modelPost.delete()
	
	return redirect(reverse('communities:index',kwargs={"page":1}))

@login_required
def viewDeleteComment(request,comment_id):
	###################################
	# Inputs:
	# request, int
	# Outputs:
	# HttpResponseRedirect
	# Utility:
	# view to delete comments
	###################################
	modelComment = get_object_or_404(Comment,id = comment_id)
	modelParentPost = modelComment.post
	modelCommentAuthor = modelComment.author

	if request.user == modelCommentAuthor:
		modelComment.delete()

	return redirect(reverse("communities:post-detail",kwargs = {'username':modelParentPost.author.username,'slug':modelParentPost.slug}))

socialPOD-django-master/communities/templates/communities/index.html
{% extends "core/base.html" %}

{% block content %}

<div class = "container border border-primary rounded p-3">
	<h1 class = 'text-center'>
		Communities
	</h1>
</div>

<br>

{% if user.is_pod_plus_member %}
<div class = "container border rounded p-3">
	<div class = "d-flex flex-row justify-content-center">
		<i class="bi bi-star mr-3 mt-1"></i>
		<a href = "{% url 'communities:leaderboard-index' %}">
			<h4 class = "text-center">
				Community Leaderboard (POD+ Exclusive)
			</h4>
		</a>
		<i class="bi bi-star ml-3 mt-1"></i>
	</div>
</div>
{% endif %}

<br>

<div class = "container border rounded p-3">
	<a href = "{% url 'communities:post-prepare' %}">
		<h4 class ="text-center">
			Create a post.
		</h4>
	</a>
</div>

<br>

<div class = "container border border rounded p-3">
	<div>
		<h4 class = "text-center">Recent posts:</h4>
	</div>
	
	<div class = "container" id = "div__posts-container" >
		{% include 'communities/t/posts.html' %}
	</div>

</div>


{% include 'communities/t/jPostActions.html' %}

{% endblock content %}

{% block javascript %}

<script>

function ajax_update_url(e){
	strUrl = e.getAttribute("data-url");
	let divPostContainer = document.getElementById('div__posts-container');

	$.ajax({
		type: 'GET',
		url: strUrl,
		dataType:'json',
		success:function(data){
			// reload posts
			divPostContainer.innerHTML = data.posts_html;
			// update url
			window.history.pushState(null,"",strUrl);
		},

	})
}

</script>

{% endblock %}

socialPOD-django-master/communities/templates/communities/leaderboard.html
{% extends 'core/base.html' %}

{% block content %}

<div class = "container border border-primary rounded p-3">
	<div class = "d-flex flex-row">
		<h1>
			<i class="bi bi-award"></i>
		</h1>
		<h1 class = "container text-center">
			Leaderboard
		</h1>
		<h1>
			<i class="bi bi-award"></i>
		</h1>
	</div>
</div>

<br>

<div class = "container border rounded p-3">
	<h3 class = "text-center">
		Weekly Rankings
	</h3>
	<div>
		<div>
			<h4>
				Most Points:
			</h4>
		</div>
		<hr>
		<div>
			<h4>
				Most Users Helped:
			</h4>
		</div>
	</div>
</div>

<br>

<div class = 'container border rounded p-3'>
	<h3 class = "text-center">
		Your Weekly Rankings
	</h3>
	<div>
		<div>
			<h4>
				Points:
			</h4>
		</div>
	</div>
	<hr>
	<div>
		<h4>
			Users Helped
		</h4>
	</div>
</div>

{% endblock %}

socialPOD-django-master/communities/templates/communities/post_detail.html
{% extends "core/base.html" %}

{% block content %}

{% include 'communities/t/tPost.html' %}

{% include 'communities/t/jPostActions.html' %}

<br>

<div class = "container border rounded p-3">
	<a href = "{% url 'communities:index' 1 %}">
		<h4 class = 'text-center'>
			Back to Communities
		</h4>
	</a>
</div>

{% endblock content %}

socialPOD-django-master/communities/templates/communities/post_prepare.html
{% extends "core/base.html" %}

{% block content %}

<div class = "container border rounded p-3">
	<h1 class = "text-center">Create a post.</h1>
	<form method = "POST" action = "{% url 'communities:post-create' %}">
		{% csrf_token %}
		<div class = "form-group">
			<label for = "tTitle">Post Title</label>
			<input type='text' name = "title" id = "tTitle" class = "form-control">
			<small id = "tTitleHelp">Write something that summarizes your post.</small>
		</div>
		<div class = "form-group">
			<label for = "taText">Post Text</label>
			<textarea name = "text" class = "form-control" rows = 4></textarea>
			<small id = "taTextHelp">Write the content of your post here.</small>
		</div>
		<br>
		<div class = "container">
			<div class = "row">
				<button type = "submit" class = "btn btn-primary">Submit</button>
			</div>
		</div>
	</form>
</div>

{% endblock %}

socialPOD-django-master/communities/templates/communities/profile.html
{% extends "core/base.html" %}

{% block content %}

{% if modelViewedUser == user %}
<div class = "text-center container border rounded alert alert-primary">
	This is how you appear publicly.
</div>
{% endif %}

<div class = "container border rounded p-3">
<div style="align-items:flex-start;">
	<div style="display:inline-flex">
		<div>
			<img class = "rounded-circle" style="width:5rem;height:5rem;" src = "{{modelViewedUser.profile_picture.url}}">
		</div>
		<div class = 'ml-3 my-auto'>
			<h2 class = "account-heading mb-0">
				{{modelViewedUser.username}}
			</h2>
			
			{% if modelViewedUser != user and modelViewedUser in user.follows.all %}
			<p class = "mt-0" 
			data-url = "{% url 'communities:follow-add-remove' modelViewedUser.username %}" id = "p__follow-unfollow-user">
				<span class = "text-danger">
					Unfollow {{modelViewedUser.username}}?
				</span>
				{% elif modelViewedUser != user and modelViewedUser not in user.follows.all %}
				<span class = "text-success">
					Follow {{modelViewedUser.username}}?
				</span>
			</p>
			{% endif %}
		</div>
	</div>
</div>
</div>

<br>

<div class = "container border rounded p-3">
	<h3>About:</h3>
	<p>
		{{modelViewedUser.about}}
	</p>
</div>

<br>

<div class = "container border rounded p-3">
<h4>
	Stats:
</h4>
<ul>
	<li>
		Joined: {{modelViewedUser.date_joined}}
	</li>
	<li>
		Users helped: {{modelViewedUser.int_users_helped}}
	</li>
	<li>
		Days active: {{modelViewedUser.int_days_active}}
	</li>
</ul>
</div>

<br>
<div class = "container border rounded p-3">
	<h4 class = 'text-center'>
		All posts from {{modelViewedUser.username}}
	</h4>
	{% if qsPosts|length == 0 %}
		<p class = "text-muted text-center">
			Nothing yet!
		</p>
	{% else %}
		{% for modelPost in qsPosts %}
		<a href = "{{modelPost.get_absolute_url}}">
			{% include 'communities/t/tPostThumb.html' %}
		</a>
		{% endfor %}
	{% endif %}
</div>

<br>

<div class = 'container'>
	<ul class='pagination justify-content-center'>
	{% if qsPosts.has_previous %}
		<li class="mx-1"><a href='{% url "communities:profile" modelViewedUser.username qsPosts.previous_page_number %}'>Previous</a></li>
	{% else %}
		<li class='mx-1 disabled'><span >Previous</span></li>
	{% endif %}

	{% for i in qsPosts.paginator.page_range %}
		{% if qsPosts.number == i %}
		<li class='active mx-1 text-success'><span>{{ i }}</span></li>
		{% else %}
		<li class="mx-1"><a href='{% url "communities:profile" modelViewedUser.username i %}'>{{ i }}</a></li>
		{% endif %}
	{% endfor %}
	
	{% if qsPosts.has_next %}
		<li class="mx-1"><a href='{% url "communities:profile" modelViewedUser.username qsPosts.next_page_number %}' >Next</a></li>
	{% else %}
		<li class="mx-1"><span class='disabled'>Next</span></li> 
	{% endif %}
	</ul>
</div>

{% endblock %}

{% block javascript %}
<script>
	function add_remove_follow(pTag){
		let strUrl = pTag.getAttribute('data-url');
		$.ajax({
			url:strUrl,
			success: function(){
				$("#p__follow-unfollow-user").load(document.URL + ' #p__follow-unfollow-user');
			}
		})

	}

	let pTag = document.getElementById('p__follow-unfollow-user');
	pTag.addEventListener("click",()=>{
		add_remove_follow(pTag);
	})

</script>
{% endblock javascript %}