socialPOD-django-master/core/urls.py
from django.urls import path

from . import views as core_views

app_name = "core"
urlpatterns = [
	# ex: /
	path('home/index&np=<int:pg_post>&nhr=<int:pg_help_req>&ndm=<int:pg_dm>/',core_views.viewIndex,name='index'),
	# ex: /about/
	path('',core_views.viewAbout,name='about'),
	# deleting notification
	path('notifications/<str:notification_type>/<int:notification_id>/delete/',core_views.viewNotificationDelete,name="notification-delete"),

	#######################
	# Tips paths
	#######################
	# reading tip
	path('tips/<int:tip_id>/read/',core_views.viewTipRead,name='tip-read'),
	# tip archive
	path('tips/archive&pg_prev_tips=<int:pg_prev_tips>/',core_views.viewTipArchive,name='tip-archive'),

	#######################
	# AJAX paths
	#######################
	path('ajax/index/posts&pg_post=<int:pg_post>&pg_hr=<int:pg_help_req>&pg_dm=<int:pg_dm>/',core_views.aGetNotifPosts,name='ajax-index-posts'),
	path('ajax/index/help_requests&pg_post=<int:pg_post>&pg_hr=<int:pg_help_req>&pg_dm=<int:pg_dm>/',core_views.aGetNotifHelpRequests,name='ajax-index-help-requests'),
	path('ajax/index/dms&pg_post=<int:pg_post>&pg_hr=<int:pg_help_req>&pg_dm=<int:pg_dm>/',core_views.aGetNotifDms,name='ajax-index-dms'),
	path('ajax/tip/archive/get_tips&pg=<int:pg_prev_tips>/',core_views.aGetTips,name="ajax-tips-archive-prev-tips"),

]

socialPOD-django-master/fitness/urls.py
from django.urls import path
# django login logout views
from django.contrib.auth import views as auth_views

from . import views as fitness_views

app_name = "fitness"

urlpatterns = [
	# ex: /fitness/
	path('',fitness_views.viewFitnessIndex,name="index"),
]

socialPOD-django-master/food/urls.py
from django.urls import path
# django login logout views
from django.contrib.auth import views as auth_views

from . import views as food_views

app_name = "food"

urlpatterns = [
	# ex: /food/
	path('',food_views.viewFoodIndex,name="index"),
	# ex: /food/delete/4/
	path('delete/<int:id>/',food_views.viewFoodDelete,name="food-delete"),
	# ex: /food/prepare/
	path('create-prepare/',food_views.viewFoodPrepare,name="food-create-prepare"),
	# ex: /food/create/
	path('create/',food_views.viewFoodCreate,name="food-create"),
]

socialPOD-django-master/socialPOD_project/urls.py
from django.contrib import admin
from django.urls import path,include

# for mapping static file urls
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # admin urls
    path('admin/', admin.site.urls),

    ##############################
    # URLS for user created apps
    ##############################
    # core urls
    path('',include('core.urls')),
    # user urls
    path('users/',include('users.urls')),
    # newsfeed urls
    path('newsfeed/',include('newsfeed.urls')),
    # podcasts urls
    path('podcasts/',include('podcasts.urls')),
    # communities urls
    path('communities/',include('communities.urls')),
    # food urls
    path('food/',include('food.urls')),
    # fitness urls
    path('fitness/',include('fitness.urls')),
]


# linking media root
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

socialPOD-django-master/users/urls.py
from django.urls import path
# django login logout views
from django.contrib.auth import views as auth_views

from . import views as users_views

app_name = "users"

urlpatterns = [
	#####################
	# User basic functions
	# Register, login/out
	#####################
	# redirect to login
	path('login-redirect/',users_views.viewLoginRedirect,name='login-redirect'),
	# ex: /users/register/
	path('register/',users_views.viewRegister,name='register'),
	# ex: /users/login/
	path('login/',auth_views.LoginView.as_view(template_name="users/login.html"),name='login'),
	# ex: /users/logout/
	path('logout/',auth_views.LogoutView.as_view(template_name="users/logout.html"),name='logout'),
	#####################
	# User profile
	#####################
	# ex: /users/profile/
	path('profile&pg_following=<int:pg_following>/',users_views.viewProfile,name='profile'),
	# ex: /users/edit-prepare/	
	path('edit-prepare/',users_views.viewProfileEditPrepare,name='profile-edit-prepare'),
	# ex: /users/edit/
	path('edit/',users_views.viewProfileEdit,name='profile-edit'),
	#####################
	# Food views
	#####################
	# ex: /users/dm/index
	path('dm/index/',users_views.viewDmIndex,name="dm-index"),
	# ex: /users/dm/prepare/
	path('dm/prepare/',users_views.viewDmPrepareSearch,name="dm-prepare"),
	# ex: /users/dm/bob/detail/
	path('dm/<str:username>/detail/',users_views.viewDmDetail,name="dm-detail"),
	# ex: /users/bob/dm/create/
	path('dm/<str:username>/create/',users_views.viewDmCreate,name="dm-create"),
	#####################
	# AJAX URLS
	#####################
	path('ajax/profile/get_followed_users&pg_following=<int:pg_following>/',users_views.aGetFollowedUsers,name="ajax-profile-get-followed-users"),
]

socialPOD-django-master/users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.contrib.auth.models import User


#############################
# Related models
#############################
from .models import CustomUser
from food.models import Food

#############################
# Forms for searching
#############################
class SearchUserForm(forms.Form):
	query = forms.CharField(label="Search",max_length=100)

#############################
# Forms for User Creation / Change
#############################

class UserRegisterForm(UserCreationForm):
	###################################
	# Form to fill when registering users
	###################################
	email = forms.EmailField()

	class Meta:
		# what model to create
		model = CustomUser
		# what fields that are to be filled
		fields = ['username','email','phone_number','password1','password2']



class CustomUserCreationForm(UserCreationForm):
	###################################
	# Form to create a new custom user
	###################################

	class Meta:
		model = CustomUser
		fields = ('username','email','phone_number','password1','password2')

class CustomUserUpdateForm(forms.ModelForm):
	email = forms.EmailField()

	class Meta:
		model = CustomUser
		fields = ['username','email','profile_picture','about']

# special bc passwords are hashed
class CustomUserUpdatePasswordForm(forms.ModelForm):
	
	class Meta:
		model = CustomUser
		fields = ['password']

socialPOD-django-master/users/views.py
#####################################
# HTML routing imports
#####################################
from django.shortcuts import render, reverse, redirect,get_object_or_404,HttpResponseRedirect

# forms
from .forms import UserRegisterForm,CustomUserUpdateForm,CustomUserUpdatePasswordForm

from core.forms import DmForm

# messages on registration / log in
from django.contrib import messages

# json / serializers
from django.http import JsonResponse

# for when need to login to view something
from django.contrib.auth.decorators import login_required

# for forbiddens
from django.http import HttpResponseForbidden

# paginators
from django.core.paginator import Paginator, EmptyPage
from django.template.loader import render_to_string

#################################
# Form imports
#################################
from .forms import SearchUserForm

#################################
# Model imports
#################################

from food.models import Food
from .models import CustomUser
from core.models import NotificationDm

#################################
# Package installs
#################################
import numpy as np
from datetime import datetime
import re


def strParsePhoneNumber(strEntry):
	return ''.join(n for n in strEntry if n.isdigit())

#################################
# Views relating to user registration
#################################

def viewRegister(request):
	###################################
	# Inputs:
	# request
	# Outputs:
	# render
	# Utility:
	# View called when registering user
	###################################
	if request.method == "POST":
		# check the phone number
		phone_number = request.POST.get("phone_number")
		pattern = re.compile(r'\d{3}-\d{3}-\d{4}')
		boolValidNumber = bool(pattern.match(phone_number))

		if not boolValidNumber:
			messages.error(request,"Please format number as 3 digits, hyphen, 3 digits, hyphen, 4 digits.")
			return redirect("users:register")

		# if get post request, instantiate form with user data
		form = UserRegisterForm(request.POST)

		if form.is_valid():
			# save the user
			form.save()

			username = form.cleaned_data.get('username')

			messages.success(request, "Account created for {}. You may now log in.".format(username))
			# redirect to this page after creation of account
			return redirect('users:login')

	else:
		form = UserRegisterForm()

	context = {
		'formRegistration':form,
	}

	return render(request,'users/register.html',context=context)


# A way to have views with arguments be login views
# kinda cheap
def viewLoginRedirect(request):

	return redirect(reverse("core:index",args=[1,1,1]))

#################################
# Views relating to user profiles
#################################

@login_required
def viewProfile(request,pg_following =1):
	###################################
	# Inputs:
	# request, pg for following users div
	# Outputs:
	# render
	# Utility:
	# view personal profile (only visible to the user themself)
	###################################

	user = request.user


	# followed users
	qsFollowedUsers = user.follows.order_by("username")

	intFollowedUsersPerPage = 1
	# paginate
	paginator_followed_users = Paginator(qsFollowedUsers,intFollowedUsersPerPage)
	try:
		qsFollowedUsers = paginator_followed_users.page(pg_following)
	except:
		qsFollowedUsers = paginator_followed_users.page(paginator_followed_users.num_pages)

	# followers
	# qsFollowerUsers = list(user.followed_by.all())

	context = {
		"dictUserStats" :{
			"strEmail": user.email,
			"strUsername":user.username,
			"strAbout": user.about,
			"boolIsPodPlusMember":user.is_pod_plus_member,
			"intPoints":user.int_points,
			"intDaysActive":user.int_days_active,
			"intUsersHelped":user.int_users_helped,
			"strDateJoined":user.date_joined,
		},
		# followed users
		"qsFollowedUsers":qsFollowedUsers,
	}

	return render(request,'users/profile.html',context = context)

# ajax view to get more followed users
def aGetFollowedUsers(request,pg_following = 1):
	intFollowedUsersPerPage = 1
	qsFollowedUsers = request.user.follows.order_by('username')
	# paginate
	paginator_followed_users = Paginator(qsFollowedUsers,intFollowedUsersPerPage)

	try:
		qsFollowedUsers = paginator_followed_users.page(pg_following)
	except EmptyPage:
		qsFollowedUsers = paginator_followed_users.page(paginator.num_pages)
	
	html_data = render_to_string(
		"users/t/profile_followed_users.html",
		{"qsFollowedUsers":qsFollowedUsers}
	)
	data = {
		"html_data":html_data,
	}

	return JsonResponse(data)

# display form to edit information
@login_required
def viewProfileEditPrepare(request):

	# allow users to edit their information

	context = {
	}

	return render(request,'users/edit.html',context = context)

# process the edited info
@login_required
def viewProfileEdit(request):

	if request.method == 'POST':

		if len(request.FILES) != 0:
			# uploaded a file
			# delete old prof pic, replace with new
			request.user.set_user_profile_picture_default()

		formUpdateForm = CustomUserUpdateForm(request.POST,request.FILES,instance=request.user)
		formUpdatePasswordForm = CustomUserUpdatePasswordForm(data=request.POST,
		instance=request.user)

		if formUpdateForm.is_valid():
			messages.success(request,"Successfully updated profile.")
			# update everything
			if formUpdatePasswordForm.is_valid():
				formUpdateForm.save()
				formUpdatePasswordForm.save()
			# else update without password
			else:
				formUpdateForm.save()
		else:
			print(formUpdateForm.errors)

	return redirect(reverse('users:profile',kwargs={"pg_following":1}))


################################
# Views related to DMs
################################

@login_required
def viewDmIndex(request):
	listmodelDmedUsers = []
	# all the distinct users you have dm'ed

	# format:
	# {"user":lastDm's pubdate}
	dictUserDmDict = {}

	for modelDm in request.user.dm_sender_set.all().order_by('-pub_date'):
		if modelDm.recipient not in dictUserDmDict:
			# add it
			dictUserDmDict[modelDm.recipient] = modelDm.pub_date

	# now loop thru recipient dms, only append to list if 
	# user not in dmDict or if user in but the dm pub date is sooner
	# if dm pub date sooner, just switch out the dm model date
	modelUserSender = None
	for modelDm in request.user.dm_recipient_set.all().order_by('-pub_date'):
		modelUserSender = modelDm.sender
		if modelUserSender not in dictUserDmDict:
			dictUserDmDict[modelDm.sender] = modelDm.pub_date
		else:
			# if the date of the last dm is less than what was recorded, update
			if dictUserDmDict[modelUserSender] < modelDm.pub_date:
				dictUserDmDict[modelUserSender] = modelDm.pub_date
	
	# now sort the dictionary by value
	dictUserDmDict = dict(sorted(dictUserDmDict.items(),key=lambda item: item[1],reverse=True))

	context = {
		"dictUserDmDict":dictUserDmDict,
	}

	return render(request,"users/dm/dm_index.html",context=context)

@login_required
def viewDmPrepareSearch(request):
	formSearchUserForm = SearchUserForm

	
	if "query" in request.GET:
		boolSearched = True
		strSearchStr = request.GET['query']

		# search for user
		listmodelMatchedUsers = []
		for modelUser in CustomUser.objects.filter(username__contains=strSearchStr):
			# can't search for self
			if modelUser != request.user:
				listmodelMatchedUsers.append(modelUser)
				

		context = {
			"formSearchUserForm":formSearchUserForm,
			"boolSearched":boolSearched,
			"strSearchStr":strSearchStr,
			"listmodelMatchedUsers":listmodelMatchedUsers,
		}

		return render(request,'users/dm/dm_prepare-search.html',context=context)
	else:
		# no query yet

		context = {
			"formSearchUserForm":formSearchUserForm,
		}
		return render(request,'users/dm/dm_prepare-search.html',context=context)

@login_required
def viewDmDetail(request,username):
	######################
	# Inputs:
	# request, username of the user to be dm'd by request.user
	######################
	modelUser = get_object_or_404(CustomUser,username=username)

	# get all the messages sent between you and user
	qsSentDms = request.user.dm_sender_set.all().filter(recipient_id=modelUser.id,room=None)
	qsRecievedDms = request.user.dm_recipient_set.all().filter(sender_id=modelUser.id,room=None)

	qsAllDms = qsSentDms.union(qsRecievedDms).order_by('pub_date')

	context = {
		"modelUser":modelUser,
		"qsAllDms":qsAllDms,
	}

	return render(request,'users/dm/dm_detail.html',context=context)


# actually creates the dm
@login_required
def viewDmCreate(request,username):
	######################
	# Inputs:
	# request, str username of the dm'ed user
	######################

	modelOtherUser = get_object_or_404(CustomUser,username=username)

	if request.method == "POST":
		# form for dm
		formDmForm = DmForm(data=request.POST)

		if formDmForm.is_valid():
			# commit = false so can continue editing fields
			modelCreatedDm = formDmForm.save(commit=False)
			# input all other fields besides text
			modelCreatedDm.sender = request.user
			modelCreatedDm.recipient = modelOtherUser
			modelCreatedDm.save()
			messages.success(request,"Direct message sent.")

			# create a notif
			modelNotif = NotificationDm(sender=request.user,recipient = modelOtherUser,
			dm=modelCreatedDm,
			text="{} has sent you a DM in \"General\".".format(request.user.username),
			)
			modelNotif.save()


		else:
			messages.error(request,"Please input text.")
			return redirect(reverse("users:dm-detail",kwargs={"username":username}))
	
	return redirect(reverse("users:dm-detail",kwargs={"username":username}))

socialPOD-django-master/users/templates/users/edit.html
{% extends 'core/base.html' %}

{% block content %}

<div class = "container border border-primary rounded p-3">
	<h2 class = 'text-center'>
		Edit Your Information
	</h2>
</div>
{{formUpdateForm}}
<br>

<div class = "container border rounded p-3">
	<form method = "POST" enctype="multipart/form-data" action = "{% url 'users:profile-edit' %}">
		{% csrf_token %}
		<div class = "form-group">
			<label for = "textUsername">Username</label>
			<input class = 'form-control' type = 'text' name='username' id = "textUsername" value="{{user.username}}">
			<small class = 'form-text text-muted'>Or leave blank if no change needed.</small>
		</div>
		<div class = "form-group">
			<label for = "emailEmail">Email</label>
			<input class = 'form-control' type = 'email' name='email' id = "emailEmail" value = "{{user.email}}">
			<small class = 'form-text text-muted'>Or leave blank if no change needed.</small>
		</div>
		<div class = "form-group">
			<label for = "textPhoneNumber">Phone Number</label>
			<input class = 'form-control' type = 'text' name='phone_number' id = "textPhoneNumber" value = "{{user.phone_number}}">
			<small class = 'form-text text-muted'>Or leave blank if no change needed.</small>
		</div>
		<div class = "form-group">
			<label for = "textAbout">About You</label>
			<input class = 'form-control' type = 'text' name='about' id = "textAbout" value = "{{user.about}}">
			<small class = 'form-text text-muted'>Or leave blank if no change needed.</small>
		</div>
		<div class = "form-group">
			<label for = "textPassword">Password</label>
			<input class = 'form-control' type = 'password' name='password' id = "textPassword">
			<small class = 'form-text text-muted'>Or leave blank if no change needed.</small>
		</div>
		<div class = "form-group">
			<label for = "fileProfilePicture">Profile Picture</label>
			<input name = 'profile_picture' type = 'file' class = 'form-control-file' id = "fileProfilePicture">
			<small class = 'form-text text-muted'>Or leave no file if no change needed.</small>
		</div>
		<button type = "submit" class = 'btn btn-outline-success'>Update</button>
	</form>
</div>

{% endblock %}

socialPOD-django-master/users/templates/users/login.html
{% extends "core/base.html" %}

{% block content %}

<div class = "container border rounded p-3">
	<form method = "POST">
		{% csrf_token %}	
		<fieldset>
			<legend>
				Log In
			</legend>
			{{form.as_p}}
		</fieldset>
		<button class="btn btn-outline-primary"  type='submit'>
			Log In
		</button>
	</form>
	<br>
</div>

<br>

<div class = "container border border rounded p-3">
	<div>
		<a href = "{% url 'users:register' %}">
			Or sign up
		</a>
	</div>
</div>

{% endblock content %}

socialPOD-django-master/users/templates/users/logout.html
{% extends "core/base.html" %}

{% block content %}

<div class = "container">
	<h1 class = "text-center">You have been logged out.</h1>
</div>

<br>
<div class = "container">
	<a href = "{% url 'users:login' %}">
		<h4 class = 'text-center'>
				Log in again.
		</h4>
	</a>
</div>


{% endblock content %}

socialPOD-django-master/users/templates/users/profile.html
{% extends 'core/base.html' %}


{% block content %}

<div style="align-items:flex-start;" class = "container border border-primary rounded p-3">
	<div style="display:inline-flex" >
		<img class = "rounded-circle" style="height:6.5rem;width:6.5rem;" src = "{{user.profile_picture.url}}">
		<div class = "ml-3 my-auto">
			<div class = "mb-0">
				<h2 class = "account-heading">
					Welcome,  <strong>{{user.username}}.</strong>
				</h2>
			</div>
			{% if user.is_pod_plus_member %}
				<div class = "mt-0">
					<p style="color:gold;">
						<strong>
							POD+ Member
						</strong>
					</p>
				</div>
			{% endif %}
		</div>
	</div>
</div>

<br>

<div class = "container border border rounded p-3">
	<a href = "{% url 'users:dm-index' %}">
		<h3 class = "text-center">
			Your DMs
		</h3>
	</a>
</div>

<br>

<div class = "container border border rounded p-3">
	<a href = "{% url 'food:index' %}">
		<h3 class = "text-center">
			Your Diet Center
		</h3>
	</a>
</div>

<br>

<div class = "container border border rounded p-3">
	<a href = "{% url 'fitness:index' %}">
		<h3 class = "text-center">
			Your Fitness Center
		</h3>
	</a>	
</div>

<br>

<div class = "container border border rounded p-3">
	<div>
		<h2 class = "text-center">
			Your Information
		</h2>
		<a href = "{% url 'users:profile-edit-prepare' %}">
			<p class = 'text-center'>
				Edit Information
			</p>
		</a>
		<a href = "{{user.get_public_profile_url}}">
			<p class = 'text-center'>
				See public profile
			</p>
		</a>
	</div>
	<hr>
	<strong>Email:</strong> {{dictUserStats.strEmail}}
	<br>
	<strong>Username:</strong> {{dictUserStats.strUsername}}
	<br>
	<strong>Days Active:</strong> {{dictUserStats.intDaysActive}}
	<br>
	{% if user.is_pod_plus_member %}
		<strong>Points:</strong> {{dictUserStats.intPoints}}
		<br>
	{% endif %}
	<strong>Date joined:</strong> {{dictUserStats.strDateJoined}}
	<br>
	<strong>About You:</strong> "{{dictUserStats.strAbout}}"
</div>

<br>

<div class = "container border border rounded pb-5 pt-1">
	<div class = "container p-3 text-center">
		<h4>Follow count: {{user.follows.count}}</h4>
	</div>
	<div>
		{% include "users/t/profile_followed_users.html" %}
	</div>
</div>


{% endblock %}

{% block javascript %}

<script>

	function ajax_update_url(e,strDivName){
		page = e.getAttribute('page');
		// url for ajax call
		strAjaxUrl = e.getAttribute('ajax-url');
		// url to change page to
		strChangeUrl = e.getAttribute('change-url');
		// get the div to update
		let divHolder = document.getElementById(strDivName);

		$.ajax({
			type:"GET",
			url:strAjaxUrl,
			dataType:'json',
			success:function(data){
				// reload div
				divHolder.innerHTML = data.html_data;
				// update url
				window.history.pushState(null,'',strChangeUrl);
			}
		})
	}
	
</script>

{% endblock %}

socialPOD-django-master/users/templates/users/register.html
{% extends "core/base.html" %}

{% block content %}

<div class = "container border border-primary rounded p-3">
	<form method = "POST">

		{% csrf_token %}
		
		<fieldset>
			<legend>Join</legend>
			{{formRegistration.as_p}}
		</fieldset>

		<div>
			<button class = "btn btn-outline-primary" type="submit">Sign Up</button>
		</div>

		<br>

		<div>
			Or <a href = "{% url 'users:login' %}" > log in</a>
		</div>

	</form>
</div>

{% endblock content %}