socialPOD-django-master/communities/urls.py
from django.urls import path

from . import views as communities_views

app_name = "communities"

# ###############################
# NOTE: Order matters!
# ###############################

urlpatterns = [
	# ex: /communities/index/
	path('index?page=<int:page>/',communities_views.viewIndex,name="index"),

	##################
	# URLS for Posts
	##################
	# CREATING A POST
	path('posts/post-create/',communities_views.viewPostCreate,name="post-create"),
	# DELETING A POST
	path('posts/post-delete/<int:post_id>',communities_views.viewPostDelete,name="post-delete"),
	# VIEWING A POST
	path('posts/view/<str:username>/<slug:slug>/',communities_views.viewPostDetail,name="post-detail"),
	# prepare a post
	path('posts/prepare/',communities_views.viewPostPrepare,name="post-prepare"),

	##################
	# URLS for Posts Actions (Like)
	##################
	path('post-like/<int:post_id>/',communities_views.viewLikeUnlikePost,name="post-like-unlike"),

	##################
	# URLS for Posts Comments
	##################
	# ex: /communities/posts/username/slug-my-post-title/create_comment/
	path('posts/<str:username>/<slug:slug>/comment-create/',communities_views.viewCreateComment,name="comment-create"),
	# ex: /communities/posts/username/slug-my-post-title/delete_comment/
	path('posts/comment-delete/<int:comment_id>/',communities_views.viewDeleteComment,name="comment-delete"),

	##################
	# URLS for Public Profiles
	##################
	# ex: /communities/profile/username/
	path('profile/<str:username>&page=<int:page>/',communities_views.viewProfile,name="profile"),
	##################
	# URLS for Following
	##################
	path('following/add_remove_follow/<str:username>/',communities_views.viewAddRemoveFollow,name="follow-add-remove"),

	##################
	# URLS for Leaderboard
	##################
	path("leaderboard/index/",communities_views.viewLeaderboardIndex,name='leaderboard-index'),
]

socialPOD-django-master/core/urls.py
from django.urls import path

from . import views as core_views

app_name = "core"
urlpatterns = [
	# ex: /
	path('home/index&np=<int:pg_post>&nhr=<int:pg_help_req>&ndm=<int:pg_dm>/',core_views.viewIndex,name='index'),
	# ex: /about/
	path('',core_views.viewAbout,name='about'),
	# deleting notification
	path('notifications/<str:notification_type>/<int:notification_id>/delete/',core_views.viewNotificationDelete,name="notification-delete"),

	#######################
	# Tips paths
	#######################
	# reading tip
	path('tips/<int:tip_id>/read/',core_views.viewTipRead,name='tip-read'),
	# tip archive
	path('tips/archive&pg_prev_tips=<int:pg_prev_tips>/',core_views.viewTipArchive,name='tip-archive'),

	#######################
	# AJAX paths
	#######################
	path('ajax/index/posts&pg_post=<int:pg_post>&pg_hr=<int:pg_help_req>&pg_dm=<int:pg_dm>/',core_views.aGetNotifPosts,name='ajax-index-posts'),
	path('ajax/index/help_requests&pg_post=<int:pg_post>&pg_hr=<int:pg_help_req>&pg_dm=<int:pg_dm>/',core_views.aGetNotifHelpRequests,name='ajax-index-help-requests'),
	path('ajax/index/dms&pg_post=<int:pg_post>&pg_hr=<int:pg_help_req>&pg_dm=<int:pg_dm>/',core_views.aGetNotifDms,name='ajax-index-dms'),
	path('ajax/tip/archive/get_tips&pg=<int:pg_prev_tips>/',core_views.aGetTips,name="ajax-tips-archive-prev-tips"),

]

socialPOD-django-master/newsfeed/urls.py
from django.urls import path
# django login logout views

from . import views as newsfeed_views

app_name = "newsfeed"

urlpatterns = [
    # ex: /newsfeed/index/
    path('index&page=<int:page>/',newsfeed_views.viewIndex,name="index"),
	##################
	# URLS for Ask for Help
	##################
    # ex: /newfeed/help-request/lex/my-title
    path('request-help/<str:username>/<slug:slug>/',newsfeed_views.viewHelpRequestDetail,name="help-request-detail"),
    # ex: /newsfeed/request-help/tag/my-tag 
    path('request-help/by-tag/tag/<str:tag>/',newsfeed_views.viewHelpRequestDetailTag,name="help-request-index-tag"),
	# ex: /newsfeed/request_help
	path('request-help/',newsfeed_views.viewHelpRequestPrepare,name="help-request-prepare"),
	# creating a request for help
	path('request-help/create/',newsfeed_views.viewHelpRequestCreate,name="help-request-create"),
	# delete help request
	path('request-help/<str:username>/<slug:slug>/delete/',newsfeed_views.viewHelpRequestDelete,name="help-request-delete"),

	# see all the help requests that you have where
	# you have been accepted
	path('request-help/accepted-requests/',newsfeed_views.viewHelpRequestAccepted,name="help-request-accepted"),

	# prepare to reset user
	path('request-help/<str:username>/<slug:slug>/reset-prepare/',newsfeed_views.viewHelpRequestAcceptedUserResetPrepare,name="help-request-accepted-user-reset-prepare"),
	# actually reset user
	path('request-help/<str:username>/<slug:slug>/reset/',newsfeed_views.viewHelpRequestAcceptedUserReset,name="help-request-accepted-user-reset"),

	##################
	# URLS for Help Request Offers
	##################
	# creating a help request offer
	path('request-help/<str:username>/<slug:slug>/offer/create/',newsfeed_views.viewHelpRequestOfferCreate,name="help-request-offer-create"),
	# viewing a help request offer
	path('request-help/<str:username>/<slug:slug>/offer/<int:id>/detail/',newsfeed_views.viewHelpRequestOfferDetail,name="help-request-offer-detail"),
	# accept a help request offer
	path('request-help/<str:username>/<slug:slug>/offer/<int:id>/accept/',newsfeed_views.viewHelpRequestOfferAccept,name="help-request-offer-accept"),
	# reject help request offer
	path('request-help/<str:username>/<slug:slug>/offer/<int:id>/reject/',newsfeed_views.viewHelpRequestOfferReject,name="help-request-offer-reject"),
	# remove accepted offer prepare
	# note that both the creator of the help request offer AND the creator of the help request can remove offers
	# remove accepted offer
	path('request-help/<str:username>/<slug:slug>/offer/<int:id>/delete/',newsfeed_views.viewHelpRequestOfferDelete,name='help-request-offer-delete'),

	##################
	# URLs for dms
	##################
	# detail a conversation
	path('dm/<str:hr_author_username>&<str:hr_accepted_user_username>/<str:room_name>/',newsfeed_views.viewDmDetail,name='help-request-dm-detail'),
	# create a dm
	path('dm/<str:hr_author_username>&<str:hr_accepted_user_username>/<str:room_name>/create/',newsfeed_views.viewDmCreate,name='help-request-dm-create'),

	##################
	# URLS for old Help Requests
	##################
	path('archive/',newsfeed_views.viewHelpRequestArchiveDetail,name="help-request-archive-detail"),
]

socialPOD-django-master/podcasts/urls.py
from django.urls import path

from . import views as podcasts_views

###################################
# Url mappings for podcasts app
###################################

app_name = "podcasts"

urlpatterns = [
	# ex: /podcasts/index/
	path('index',podcasts_views.viewIndex,name="index"),
]

socialPOD-django-master/socialPOD_project/urls.py
from django.contrib import admin
from django.urls import path,include

# for mapping static file urls
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # admin urls
    path('admin/', admin.site.urls),

    ##############################
    # URLS for user created apps
    ##############################
    # core urls
    path('',include('core.urls')),
    # user urls
    path('users/',include('users.urls')),
    # newsfeed urls
    path('newsfeed/',include('newsfeed.urls')),
    # podcasts urls
    path('podcasts/',include('podcasts.urls')),
    # communities urls
    path('communities/',include('communities.urls')),
    # food urls
    path('food/',include('food.urls')),
    # fitness urls
    path('fitness/',include('fitness.urls')),
]


# linking media root
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

socialPOD-django-master/users/urls.py
from django.urls import path
# django login logout views
from django.contrib.auth import views as auth_views

from . import views as users_views

app_name = "users"

urlpatterns = [
	#####################
	# User basic functions
	# Register, login/out
	#####################
	# redirect to login
	path('login-redirect/',users_views.viewLoginRedirect,name='login-redirect'),
	# ex: /users/register/
	path('register/',users_views.viewRegister,name='register'),
	# ex: /users/login/
	path('login/',auth_views.LoginView.as_view(template_name="users/login.html"),name='login'),
	# ex: /users/logout/
	path('logout/',auth_views.LogoutView.as_view(template_name="users/logout.html"),name='logout'),
	#####################
	# User profile
	#####################
	# ex: /users/profile/
	path('profile&pg_following=<int:pg_following>/',users_views.viewProfile,name='profile'),
	# ex: /users/edit-prepare/	
	path('edit-prepare/',users_views.viewProfileEditPrepare,name='profile-edit-prepare'),
	# ex: /users/edit/
	path('edit/',users_views.viewProfileEdit,name='profile-edit'),
	#####################
	# Food views
	#####################
	# ex: /users/dm/index
	path('dm/index/',users_views.viewDmIndex,name="dm-index"),
	# ex: /users/dm/prepare/
	path('dm/prepare/',users_views.viewDmPrepareSearch,name="dm-prepare"),
	# ex: /users/dm/bob/detail/
	path('dm/<str:username>/detail/',users_views.viewDmDetail,name="dm-detail"),
	# ex: /users/bob/dm/create/
	path('dm/<str:username>/create/',users_views.viewDmCreate,name="dm-create"),
	#####################
	# AJAX URLS
	#####################
	path('ajax/profile/get_followed_users&pg_following=<int:pg_following>/',users_views.aGetFollowedUsers,name="ajax-profile-get-followed-users"),
]

socialPOD-django-master/core/forms.py
# forms for models
from django import forms

#############################
# Related models
#############################
from .models import Dm

#############################
# forms for Dms
#############################
class DmForm(forms.ModelForm):
	# form to create a dm
	class Meta:
		model = Dm

		fields = [
			'text',
		]
		exclude = ()

socialPOD-django-master/core/templates/core/about.html
{% extends "core/base.html" %}


{% block content %}

<div class = "container border border-primary rounded p-3">
    <h1 class = 'text-center'>
        About
    </h1>
</div>

<br>

<div class = "container border rounded p-3">
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Id delectus eos, repellat quod labore perferendis dicta nihil ullam odit architecto at inventore eum, magnam dolor voluptatibus, porro recusandae veniam repudiandae?
</div>

{% endblock content %}

socialPOD-django-master/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

	<!-- Bootstrap icons -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">

	<!-- ChartJS -->
	<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4"></script>
	<!-- SocialPOD custom styles -->
	<link rel="stylesheet" type = "text/css" href = "{% static 'core/style.css' %}">


	{% if strTitle %}
		<title>socialPOD - {{ strTitle }}</title>
	{% else %}
		<title>socialPOD</title>
	{% endif %}
</head>
<body>

<!-- 
Basic navbar to show it is possible
-->
<p>{{ request.build_absolute_uri }}</p>

<span id = "base__hidden-path-tracker" style = "display:none" data-url = "{{request.get_full_path}}"></span>

{% if user.is_developer %}
	<p style = 'color:green'>developer {{user.user_name}}</p>
	<a href = "{% url 'admin:index' %}">
		Administration
	</a>

{% elif user.is_staff %}
	<p style = "color:green">staff {{user.user_name}}</p>
{% endif %}

<nav class="navbar" id = "navbar__main">
	<div class = "container-fluid">

		<a class = "navbar-header" href = "{% url 'core:about' %}">
			<img src = "{% static 'core/images/core/arnold_school_of_public_health.jpg' %}" alt = "arnold_school_of_public_health.jpg">
		</a>

		{% if user.is_authenticated %}
			<div style="display:grid;">
				<a style="grid-column:1;grid-row:1;" class = "navbar-text navbar__main__a-tag" href = "{% url 'core:index' 1 1 1 %}" data-str = "home">
					Home
				</a>
				<div style = "grid-column-start: 2;grid-row:1;">
					<span style="color:white">
						{{user.get_notification_count}}
					</span>
				</div>
			</div>

			<a class = "navbar-text navbar__main__a-tag" href = "{% url 'communities:index' 1 %}" data-str = "communities">
				Communities
			</a>
			<a class = "navbar-text navbar__main__a-tag" href = "{% url 'newsfeed:index' 1 %}" data-str ="newsfeed" >
				Newsfeed
			</a>
			<a class = "navbar-text navbar__main__a-tag" href = "{% url 'podcasts:index' %}" data-str ="podcasts">
				Podcasts & Tips
			</a>
			<a class = "navbar-text navbar__main__a-tag" href = "{% url 'users:profile' 1 %}" data-str ="users">
				Profile
			</a>
			<a class = "navbar-text navbar__main__a-tag" href = "{% url 'users:logout' %}">
				Logout
			</a>
		{% else %}
			<a class = "navbar-text navbar__main__a-tag" href = "{% url 'users:register' %}">
				Register
			</a>
			<a class = "navbar-text navbar__main__a-tag" href = "{% url 'users:login' %}">
				Login
			</a>
		{% endif %}
	</div>

</nav>

<!-- If messages, display -->
<div class = "div__GLOBAL_CONTENT" >
	{% if messages %}
		{% for message in messages %}
			<div class = "alert alert-{{message.tags}} base__div-alert">
				<div class = "d-flex justify-content-between">
					<div>
						{{message}}
					</div>
					<div>
						<i class = 'bi bi-x base__i-x-clicker'></i>
					</div>
				</div>
			</div>
		{% endfor %}
	{% endif %}

	{% block content %}{% endblock content %}
	

	{% block javascript %}{% endblock javascript %}
</div>

</body>
</html>

<script>

	function base__removeMsg(){
		let arrdivMsgs = document.getElementsByClassName("base__div-alert");

		for(let divMsg of arrdivMsgs){
			ixClicker = divMsg.getElementsByClassName("base__i-x-clicker")[0];
			ixClicker.addEventListener("click",()=>{
				divMsg.remove();
			})
		}
	}

	function base__updateNavBarCurrentTab(){
		let strCurrUrl = document.getElementById("base__hidden-path-tracker").getAttribute("data-url");
		let strParsedUrl = strCurrUrl.split("/")[1];

		let arrNavbarATags = document.getElementsByClassName("navbar__main__a-tag");
		for(let atag of arrNavbarATags){
			let strTagDataStr = atag.getAttribute("data-str");
			if(strTagDataStr == strParsedUrl){
				atag.style.color = "#868686";
			}
		}

	}
	document.addEventListener("DOMContentLoaded",()=>{
		base__updateNavBarCurrentTab();
		base__removeMsg();
	})
</script>

socialPOD-django-master/core/templates/core/index.html
{% extends "core/base.html" %}
{% block content %}

{% if modelTipOfDay %}
	<div class = "container border rounded p-3">
		<h4 class = "text-center">
			Tip of the day for {{strDate}}
		</h4>

	{% include 'core/t/tips/tTipIndex.html' %}
	</div>

	<br>
{% endif %}

<div class = "container border rounded p-3">
	{% include 'core/t/index_dms.html' %}
</div>

<br>

<div class = "container border rounded p-3">
	{% include 'core/t/index_posts.html' %}
</div>

<br>

<div class = "container border rounded p-3">
	{% include 'core/t/index_help_requests.html' %}
</div>
{% endblock content %}

{% block javascript %}

<script>

	function ajax_update_url(e,strDivName){
		// url for ajax call
		strAjaxUrl = e.getAttribute('ajax-url');
		// url to change page to
		strChangeUrl = e.getAttribute('change-url');
		// get the div to update
		let divHolder = document.getElementById(strDivName);

		$.ajax({
			type:"GET",
			url:strAjaxUrl,
			dataType:'json',
			success:function(data){
				// reload div
				divHolder.innerHTML = data.html_data;
				// update url
				window.history.pushState(null,'',strChangeUrl);
			}
		})
	}
	
</script>

{% endblock %}