socialPOD-django-master/core/urls.py
from django.urls import path

from . import views as core_views

app_name = "core"
urlpatterns = [
	# ex: /
	path('home/index&np=<int:pg_post>&nhr=<int:pg_help_req>&ndm=<int:pg_dm>/',core_views.viewIndex,name='index'),
	# ex: /about/
	path('',core_views.viewAbout,name='about'),
	# deleting notification
	path('notifications/<str:notification_type>/<int:notification_id>/delete/',core_views.viewNotificationDelete,name="notification-delete"),

	#######################
	# Tips paths
	#######################
	# reading tip
	path('tips/<int:tip_id>/read/',core_views.viewTipRead,name='tip-read'),
	# tip archive
	path('tips/archive&pg_prev_tips=<int:pg_prev_tips>/',core_views.viewTipArchive,name='tip-archive'),

	#######################
	# AJAX paths
	#######################
	path('ajax/index/posts&pg_post=<int:pg_post>&pg_hr=<int:pg_help_req>&pg_dm=<int:pg_dm>/',core_views.aGetNotifPosts,name='ajax-index-posts'),
	path('ajax/index/help_requests&pg_post=<int:pg_post>&pg_hr=<int:pg_help_req>&pg_dm=<int:pg_dm>/',core_views.aGetNotifHelpRequests,name='ajax-index-help-requests'),
	path('ajax/index/dms&pg_post=<int:pg_post>&pg_hr=<int:pg_help_req>&pg_dm=<int:pg_dm>/',core_views.aGetNotifDms,name='ajax-index-dms'),
	path('ajax/tip/archive/get_tips&pg=<int:pg_prev_tips>/',core_views.aGetTips,name="ajax-tips-archive-prev-tips"),

]

socialPOD-django-master/newsfeed/urls.py
from django.urls import path
# django login logout views

from . import views as newsfeed_views

app_name = "newsfeed"

urlpatterns = [
    # ex: /newsfeed/index/
    path('index&page=<int:page>/',newsfeed_views.viewIndex,name="index"),
	##################
	# URLS for Ask for Help
	##################
    # ex: /newfeed/help-request/lex/my-title
    path('request-help/<str:username>/<slug:slug>/',newsfeed_views.viewHelpRequestDetail,name="help-request-detail"),
    # ex: /newsfeed/request-help/tag/my-tag 
    path('request-help/by-tag/tag/<str:tag>/',newsfeed_views.viewHelpRequestDetailTag,name="help-request-index-tag"),
	# ex: /newsfeed/request_help
	path('request-help/',newsfeed_views.viewHelpRequestPrepare,name="help-request-prepare"),
	# creating a request for help
	path('request-help/create/',newsfeed_views.viewHelpRequestCreate,name="help-request-create"),
	# delete help request
	path('request-help/<str:username>/<slug:slug>/delete/',newsfeed_views.viewHelpRequestDelete,name="help-request-delete"),

	# see all the help requests that you have where
	# you have been accepted
	path('request-help/accepted-requests/',newsfeed_views.viewHelpRequestAccepted,name="help-request-accepted"),

	# prepare to reset user
	path('request-help/<str:username>/<slug:slug>/reset-prepare/',newsfeed_views.viewHelpRequestAcceptedUserResetPrepare,name="help-request-accepted-user-reset-prepare"),
	# actually reset user
	path('request-help/<str:username>/<slug:slug>/reset/',newsfeed_views.viewHelpRequestAcceptedUserReset,name="help-request-accepted-user-reset"),

	##################
	# URLS for Help Request Offers
	##################
	# creating a help request offer
	path('request-help/<str:username>/<slug:slug>/offer/create/',newsfeed_views.viewHelpRequestOfferCreate,name="help-request-offer-create"),
	# viewing a help request offer
	path('request-help/<str:username>/<slug:slug>/offer/<int:id>/detail/',newsfeed_views.viewHelpRequestOfferDetail,name="help-request-offer-detail"),
	# accept a help request offer
	path('request-help/<str:username>/<slug:slug>/offer/<int:id>/accept/',newsfeed_views.viewHelpRequestOfferAccept,name="help-request-offer-accept"),
	# reject help request offer
	path('request-help/<str:username>/<slug:slug>/offer/<int:id>/reject/',newsfeed_views.viewHelpRequestOfferReject,name="help-request-offer-reject"),
	# remove accepted offer prepare
	# note that both the creator of the help request offer AND the creator of the help request can remove offers
	# remove accepted offer
	path('request-help/<str:username>/<slug:slug>/offer/<int:id>/delete/',newsfeed_views.viewHelpRequestOfferDelete,name='help-request-offer-delete'),

	##################
	# URLs for dms
	##################
	# detail a conversation
	path('dm/<str:hr_author_username>&<str:hr_accepted_user_username>/<str:room_name>/',newsfeed_views.viewDmDetail,name='help-request-dm-detail'),
	# create a dm
	path('dm/<str:hr_author_username>&<str:hr_accepted_user_username>/<str:room_name>/create/',newsfeed_views.viewDmCreate,name='help-request-dm-create'),

	##################
	# URLS for old Help Requests
	##################
	path('archive/',newsfeed_views.viewHelpRequestArchiveDetail,name="help-request-archive-detail"),
]

socialPOD-django-master/socialPOD_project/urls.py
from django.contrib import admin
from django.urls import path,include

# for mapping static file urls
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # admin urls
    path('admin/', admin.site.urls),

    ##############################
    # URLS for user created apps
    ##############################
    # core urls
    path('',include('core.urls')),
    # user urls
    path('users/',include('users.urls')),
    # newsfeed urls
    path('newsfeed/',include('newsfeed.urls')),
    # podcasts urls
    path('podcasts/',include('podcasts.urls')),
    # communities urls
    path('communities/',include('communities.urls')),
    # food urls
    path('food/',include('food.urls')),
    # fitness urls
    path('fitness/',include('fitness.urls')),
]


# linking media root
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

socialPOD-django-master/newsfeed/forms.py
from django import forms
#####################################
# Necessary models
#####################################
from .models import HelpRequest, HelpRequestOffer

class HelpRequestForm(forms.ModelForm):
	class Meta:
		model = HelpRequest

		fields = [
			"title",
			"text",
			"tags",
		]
		exclude = ()

class HelpRequestOfferForm(forms.ModelForm):
	class Meta:
		model = HelpRequestOffer

		fields = [
			"text",
		]

		exclude = ()

socialPOD-django-master/newsfeed/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required

#####################################
# necesssary imports
#####################################
from django.contrib import messages
from django.utils import timezone
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage

# json
from django.http import JsonResponse
# template loading
from django.template.loader import render_to_string

############################
# Necessary Models
############################

# newsfeed models
from newsfeed.models import HelpRequest,HelpRequestOffer

# communities models
from communities.models import Post
# users models
from users.models import CustomUser
##############
# Core models
# notifications, feedback
##############
# notifications
from core.models import (NotificationHelpRequest,NotificationDm, 
FeedbackHelpRequestOffer, FeedbackHelpRequest,
FeedbackHelpRequestOffer,Dm,RoomDm)

############################
# Necessary Forms
############################
from newsfeed.forms import HelpRequestForm,HelpRequestOfferForm
from core.forms import DmForm

############################
# Common functions
############################
from newsfeed.common_functions import CommonFunctions

def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

@login_required
def viewIndex(request,page=1):
    ###################################
    # Inputs:
    # request
    # Outputs:
    # render
    # Utility:
    # view called when go to index page of newsfeed
    ###################################

    # variable for how many days 
    intWithinDays = 7

    # list of all recent posts
    listRecentPosts = []
    for modelPost in Post.objects.all().order_by('-pub_date'):
        if modelPost.boolWithinXDays(1) and modelPost.author != request.user:
            listRecentPosts.append(modelPost)
    
    # list of unfilled help requests
    # right now it has every single request, in reality may want to limit
    qsUnfilledHelpRequests = HelpRequest.objects.filter(accepted_user = None).order_by('-pub_date')

    # now we paginate
    intHelpRequestsPerPage = 2
    paginator = Paginator(qsUnfilledHelpRequests,intHelpRequestsPerPage)
    # paginate based on number of help requests
    try:
        qsUnfilledHelpRequests = paginator.page(page)
    except EmptyPage:
        # if exceed limit go to last page
        qsUnfilledHelpRequests = paginator.page(paginator.num_pages)

    listLastNFollowedUserPosts = []
    # loop thru followed users, get their recent posts
    for modelUser in request.user.follows.all():
        # loop thru their posts
        for modelPost in modelUser.created_post_set.all():
            # if within, append
            if modelPost.boolWithinXDays(intWithinDays):
                listLastNFollowedUserPosts.append(modelPost)

    context = {
        "listRecentPosts":listRecentPosts,
        'qsUnfilledHelpRequests':qsUnfilledHelpRequests,
        "listLastNFollowedUserPosts":listLastNFollowedUserPosts,
        "page":page,
    }

    if is_ajax(request):
        help_requests_html = render_to_string(
            "newsfeed/t/index_help_requests.html",
            {"qsUnfilledHelpRequests":qsUnfilledHelpRequests}
        )
        data = {
            'data_html':help_requests_html,
        }
        return JsonResponse(data)

    return render(request,'newsfeed/index.html',context = context)

@login_required
def viewHelpRequestDetailTag(request, tag):
    ###################################
    # Inputs:
    # request, str tag
    # Outputs:
    # render
    # Utility:
    # view called when looking at help requests by tag
    ###################################

    # list of unfilled help requests
    # right now it has every single request, in reality may want to limit
    listUnfilledHelpRequests = []
    for modelHelpRequest in HelpRequest.objects.all().order_by("-pub_date"):
        if not modelHelpRequest.boolWasRespondedTo() and (tag in modelHelpRequest.get_parsed_tags()):
            listUnfilledHelpRequests.append(modelHelpRequest)
    context = {
        "strSelectedTag":tag,
        "listUnfilledHelpRequests":listUnfilledHelpRequests,
    }
    return render(request,'newsfeed/help_request/detail_tag.html',context)

@login_required
def viewHelpRequestDetail(request,username,slug):
    ###################################
    # Inputs:
    # request, str username, str slug
    # Outputs:
    # render
    # Utility:
    # view called when seeing an individual help reqeust
    ###################################

    # View an individual help request
    modelHelpRequestAuthor = get_object_or_404(CustomUser,username = username)
    modelHelpRequest = get_object_or_404(HelpRequest,slug=slug,author=modelHelpRequestAuthor)

    # get all the offers
    listmodelHelpRequestOffers = modelHelpRequest.help_request_offer_set.all()

    # the offer that was accepted, if present
    modelHelpRequestOfferAccepted = None

    # the offer created by someone who already made an offer, if present
    modelHelpRequestOffer = None

    # get the offer that won, if present
    for modelLoopedOffer in listmodelHelpRequestOffers:
        # each user can only create one help request offer, so only need to check user
        if modelLoopedOffer.author == modelHelpRequest.accepted_user:
            modelHelpRequestOfferAccepted = modelLoopedOffer
        # if request user made offer, show them it
        if modelLoopedOffer.author == request.user:
            modelHelpRequestOffer = modelLoopedOffer
    
    # get the roomDM, if present
    modelRoomDm = None 
    try:
        modelRoomDm = get_object_or_404(RoomDm, name=modelHelpRequest.slug,
        author = modelHelpRequest.author,partner = modelHelpRequest.accepted_user)
    except:
        pass

    boolCreatedHelpRequestOffer = False 
    
    if modelHelpRequestOffer != None:
        boolCreatedHelpRequestOffer = True

    context = {
        "modelHelpRequest":modelHelpRequest,
        "modelHelpRequestAuthor":modelHelpRequestAuthor,

        'modelHelpRequestOfferAccepted':modelHelpRequestOfferAccepted,
		# if present
		'modelHelpRequestOffer':modelHelpRequestOffer,
        # test if user who sees page created an offer or not
        "boolCreatedHelpRequestOffer":boolCreatedHelpRequestOffer,

        "listmodelHelpRequestOffers":listmodelHelpRequestOffers,

        # if room created, show it to author and partner
        "modelRoomDm":modelRoomDm,
    }
    return render(request,"newsfeed/help_request/detail.html",context)

@login_required
def viewHelpRequestPrepare(request):
    ###################################
    # Inputs:
    # request
    # Outputs:
    # render
    # Utility:
    # view called when requesting help
    ###################################

    return render(request, "newsfeed/request_help.html")

#######################################################
#
# Utility views
#
#######################################################

# delete help request
@login_required
def viewHelpRequestDelete(request, username,slug):
    ###################################
    # Inputs:
    # request, username of author, slug of post
    # Outputs:
    # redirect
    # Utility:
    # delete a help request
    ###################################

    modelAuthor = get_object_or_404(CustomUser,username=username)

    modelHelpRequest = get_object_or_404(HelpRequest,author = modelAuthor,slug=slug)
    modelHelpRequestAuthor = modelHelpRequest.author

    if(request.user == modelHelpRequestAuthor):
        messages.success(request,"Help Request successfully deleted.")
        modelHelpRequest.delete()

    return redirect(reverse("newsfeed:index",kwargs={'page':1}))

@login_required
def viewHelpRequestCreate(request):
    ###################################
    # Inputs:
    # request
    # Outputs:
    # render
    # Utility:
    # view called when requesting help
    ###################################

    # This is a list of all possible tags in the create help request form
    listPossibleTags = ["nutrition","diet","routine"]

    if request.method == "POST":
        # get the user who wants help
        modelUser = request.user
        # get title for post
        strTitle = request.POST['title']
        # get the content
        strTextContent = request.POST['text']

        # get the tags and concat them
        strConcatedTags = ""
        for strPossibleTag in listPossibleTags:
            if strPossibleTag in request.POST.keys():
                strConcatedTags += (strPossibleTag) + "$"
        if(strConcatedTags != ""):
            # if not empty, remove the last "-"
            strConcatedTags = strConcatedTags[:-1]

        # create help request form so we can create object
        formCreateHelpRequest = HelpRequestForm()
        # commit = false so we can edit attributes    
        modelCreatedHelpRequest = formCreateHelpRequest.save(commit = False)
        # edit attributes
        modelCreatedHelpRequest.author = modelUser
        modelCreatedHelpRequest.title = strTitle
        modelCreatedHelpRequest.text = strTextContent
        # if tags, put them
        if strConcatedTags != "":
            modelCreatedHelpRequest.tags = strConcatedTags

        # save the model when all attributes edited
        modelCreatedHelpRequest.save()

        # create an alert for all users
        # NOTE: 
        # at moment just filtering for active users
        for modelLoopedUser in CustomUser.objects.filter(is_active = True):
            # dont send yourself a notification
            if modelLoopedUser != request.user:
                modelNotificationToLoopedUser = NotificationHelpRequest(sender=request.user,recipient=modelLoopedUser,
                    text = "{} created help request \"{}\". See if you can help!".format(request.user.username,strTitle)
                )
                # associate with a help request

socialPOD-django-master/newsfeed/templates/newsfeed/index.html
{% extends "core/base.html" %}

{% block content %}

<div class = "container text-center border border-primary rounded p-3">
	<div class = "d-flex flex-row">
		<h1>
			<i class="bi bi-newspaper"></i>
		</h1>
		<h1 class = 'container text-center'>
			Newsfeed
		</h1>
		<h1>
			<i class="bi bi-newspaper"></i>
		</h1>
	</div>
</div>

<br>

<div class = "container border rounded p-3">
	<h4 class = "text-center">
		<a href = "{% url 'newsfeed:help-request-prepare' %}">
			Request Help
		</a>
	</h4>
</div>

<br>
<div class = "container border rounded p-3">
	<h4 class = "text-center">
		<a href ="{% url 'newsfeed:help-request-archive-detail' %}">
			View Your Requests
		</a>
	</h4>
</div>

<br>

<div class = "container border rounded p-3">
	<h4 class = "text-center">
		<a href ="{% url 'newsfeed:help-request-accepted' %}">
			View Your Accepted Offers
		</a>
	</h4>
</div>

<br>

<div class = "container border border rounded p-3">
	<h4 class = 'text-center'>
		Recent Help Requests
	</h4>
	<div id = "div__help-requests-holder">
		{% include 'newsfeed/t/index_help_requests.html' %}
	</div>
</div>

<br>

<div class = "container border border rounded p-3">
	<h4 class = 'text-center'>
		See what your followed users are posting.
	</h4>
	{% if listLastNFollowedUserPosts|length == 0 %}
		<p class = "text-muted text-center">
			Looks like theres nothing yet!
		</p>
	{% else %}
		{% for modelPost in listLastNFollowedUserPosts %}
			{% include "communities/t/tPostThumb.html" %}
		{% endfor %}
	{% endif %}
</div>

<br>

<div class = "container border border rounded p-3">
	<h4 class = 'text-center'>
		Most recent posts today.
	</h4>
	{% if listRecentPosts|length == 0 %}
		<p class = "text-muted text-center">
			Looks like theres nothing yet!
		</p>
	{% endif %}
	{% for modelPost in listRecentPosts %}

		{% include "communities/t/tPostThumb.html" %}

	{% endfor %}
</div>


{% endblock content %}

{% include 'newsfeed/t/jsHelpRequest.html' %}

{% block javascript %}

<script>

function ajax_update_url(e,divName){
	page = e.getAttribute('page');
	strUrl = e.getAttribute('data-url');
	let divHolder = document.getElementById(divName);

	$.ajax({
		type:"GET",
		url:strUrl,
		dataType:'json',
		// all the args for url
		data:{
			'page':page,
		},
		success: function(data){
			// reload stuff
			divHolder.innerHTML = data.data_html;
			// update url
			window.history.pushState(null,"",strUrl);
		}
	})
}

</script>

{% endblock %}

socialPOD-django-master/newsfeed/templates/newsfeed/request_help.html
{% extends "core/base.html" %}

{% block content %}

<div class = "container border rounded p-3">
	<h1 class = "text-center">What would you like help with?</h1>
</div>

<br>

<div class = "container border rounded p-3">
	<h4 class = "text-center">Give some information on your problem.</h4>
	<form method = "POST" action = "{% url 'newsfeed:help-request-create' %}">
		{% csrf_token %}
		<div class = "form-group">
			<label for = "title">Title your request.</label>
			<textarea name = "title" id= "textareaProblemTitle" class = "form-control" rows = 1></textarea>
			<small id = "textareaProblemTitleHelp" class= "form-text text-muted">Write a meaningful title that captures the core of the problem.</small>
			<label for = "text">Write about your issue.</label>
			<textarea name = "text" id= "textareaProblemEntry" class = "form-control" rows = 3></textarea>
			<small id = "textareaProblemEntryHelp" class= "form-text text-muted">Summarize your problem so others can help.</small>
		</div>

		<br>
		<label>Tags:</label>			
		<div class = "container border rounded">
			<br>
			<div class = "row">
				<div class = "col-4 text-center">
					<input name = "nutrition" class = "form-check-input" type="checkbox" id= "inlineCheckBox1">
					<label class = "form-check-label pl-2" for ="inlineCheckBox1">Nutrition</label>
				</div>
				<div class = "col-4 text-center">
					<input name = "diet" class = "form-check-input" type="checkbox" id= "inlineCheckBox2">
					<label class = "form-check-label pl-2" for ="inlineCheckBox2">Diet</label>
				</div>
				<div class = "col-4 text-center">
					<input name = "routine" class = "form-check-input" type="checkbox" id= "inlineCheckBox3">
					<label class = "form-check-label pl-2" for ="inlineCheckBox2">Routine</label>
				</div>
			</div>
			<br>
		</div>
			<small id = "tagsHelp" class= "form-text text-muted">Choose tags related to your problem.</small>
		<br>
		<div class = "container">
			<div class = "row">
				<div>
					<button type = "submit" class = "btn btn-primary">Submit</button>
				</div>
			</div>
		</div>
	</form>

	<br>

</div>

{% endblock %}